name: kostku
description: A new Flutter project

# The following line prevents packages from being accidentally published to pub.dev using `flutter pub publish`.
# See https://dart.dev/tools/pub/glossary#dependency-overrides for more information.
publish_to: 'none' # Remove this line if you are publishing to pub.dev.

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.0.0  # Menggunakan Font Awesome yang mendukung null safety
  cupertino_icons: ^1.0.8  # Pastikan tidak ada masalah indentasi atau format

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
